reservoir.res: written by SWAT+ editor v3.0.8 on 2025-10-29 11:31 for SWAT+ rev.61.0.1
      id  name                          init               hyd               rel               sed               nut  
       1  res004                    initres1            res004     drawdown_days           sedres1           nutres1  
       2  res005                    initres1            res005     drawdown_days           sedres1           nutres1  
       3  res008                    initres1            res008     drawdown_days           sedres1           nutres1  
       4  res009                    initres1            res009     drawdown_days           sedres1           nutres1  
       5  res010                    initres1            res010     drawdown_days           sedres1           nutres1  
       6  res012                    initres1            res012     drawdown_days           sedres1           nutres1  
       7  res016                    initres1            res016     drawdown_days           sedres1           nutres1  
       8  res017                    initres1            res017     drawdown_days           sedres1           nutres1  
       9  res019                    initres1            res019     drawdown_days           sedres1           nutres1  
      10  res020                    initres1            res020     drawdown_days           sedres1           nutres1  
      11  res023                    initres1            res023     drawdown_days           sedres1           nutres1  
      12  res027                    initres1            res027     drawdown_days           sedres1           nutres1  
      13  res029                    initres1            res029     drawdown_days           sedres1           nutres1  
      14  res030                    initres1            res030     drawdown_days           sedres1           nutres1  
      15  res032                    initres1            res032     drawdown_days           sedres1           nutres1  
      16  res034                    initres1            res034     drawdown_days           sedres1           nutres1  
      17  res036                    initres1            res036     drawdown_days           sedres1           nutres1  
      18  res037                    initres1            res037     drawdown_days           sedres1           nutres1  
      19  res042                    initres1            res042     drawdown_days           sedres1           nutres1  
      20  res043                    initres1            res043     drawdown_days           sedres1           nutres1  
      21  res045                    initres1            res045     drawdown_days           sedres1           nutres1  
      22  res050                    initres1            res050     drawdown_days           sedres1           nutres1  
      23  res054                    initres1            res054     drawdown_days           sedres1           nutres1  
      24  res057                    initres1            res057     drawdown_days           sedres1           nutres1  
      25  res058                    initres1            res058     drawdown_days           sedres1           nutres1  
      26  res059                    initres1            res059     drawdown_days           sedres1           nutres1  
      27  res062                    initres1            res062     drawdown_days           sedres1           nutres1  
      28  res064                    initres1            res064     drawdown_days           sedres1           nutres1  
      29  res065                    initres1            res065     drawdown_days           sedres1           nutres1  
      30  res067                    initres1            res067     drawdown_days           sedres1           nutres1  
      31  res070                    initres1            res070     drawdown_days           sedres1           nutres1  
      32  res071                    initres1            res071     drawdown_days           sedres1           nutres1  
      33  res084                    initres1            res084     drawdown_days           sedres1           nutres1  
      34  res089                    initres1            res089     drawdown_days           sedres1           nutres1  
      35  res098                    initres1            res098     drawdown_days           sedres1           nutres1  
      36  res100                    initres1            res100     drawdown_days           sedres1           nutres1  
      37  res101                    initres1            res101     drawdown_days           sedres1           nutres1  
      38  res103                    initres1            res103     drawdown_days           sedres1           nutres1  
      39  res109                    initres1            res109     drawdown_days           sedres1           nutres1  
      40  res110                    initres1            res110     drawdown_days           sedres1           nutres1  
      41  res111                    initres1            res111     drawdown_days           sedres1           nutres1  
      42  res112                    initres1            res112     drawdown_days           sedres1           nutres1  
      43  res118                    initres1            res118     drawdown_days           sedres1           nutres1  
      44  res120                    initres1            res120     drawdown_days           sedres1           nutres1  
      45  res121                    initres1            res121     drawdown_days           sedres1           nutres1  
      46  res122                    initres1            res122     drawdown_days           sedres1           nutres1  
      47  res124                    initres1            res124     drawdown_days           sedres1           nutres1  
      48  res126                    initres1            res126     drawdown_days           sedres1           nutres1  
      49  res127                    initres1            res127     drawdown_days           sedres1           nutres1  
      50  res131                    initres1            res131     drawdown_days           sedres1           nutres1  
      51  res134                    initres1            res134     drawdown_days           sedres1           nutres1  
      52  res135                    initres1            res135     drawdown_days           sedres1           nutres1  
      53  res136                    initres1            res136     drawdown_days           sedres1           nutres1  
      54  res137                    initres1            res137     drawdown_days           sedres1           nutres1  
      55  res141                    initres1            res141     drawdown_days           sedres1           nutres1  
      56  res144                    initres1            res144     drawdown_days           sedres1           nutres1  
      57  res145                    initres1            res145     drawdown_days           sedres1           nutres1  
      58  res150                    initres1            res150     drawdown_days           sedres1           nutres1  
      59  res153                    initres1            res153     drawdown_days           sedres1           nutres1  
      60  res155                    initres1            res155     drawdown_days           sedres1           nutres1  
      61  res156                    initres1            res156     drawdown_days           sedres1           nutres1  
      62  res157                    initres1            res157     drawdown_days           sedres1           nutres1  
      63  res158                    initres1            res158     drawdown_days           sedres1           nutres1  
      64  res161                    initres1            res161     drawdown_days           sedres1           nutres1  
      65  res164                    initres1            res164     drawdown_days           sedres1           nutres1  
      66  res167                    initres1            res167     drawdown_days           sedres1           nutres1  
      67  res169                    initres1            res169     drawdown_days           sedres1           nutres1  
      68  res172                    initres1            res172     drawdown_days           sedres1           nutres1  
      69  res173                    initres1            res173     drawdown_days           sedres1           nutres1  
      70  res176                    initres1            res176     drawdown_days           sedres1           nutres1  
      71  res177                    initres1            res177     drawdown_days           sedres1           nutres1  
      72  res178                    initres1            res178     drawdown_days           sedres1           nutres1  
      73  res181                    initres1            res181     drawdown_days           sedres1           nutres1  
      74  res185                    initres1            res185     drawdown_days           sedres1           nutres1  
      75  res186                    initres1            res186     drawdown_days           sedres1           nutres1  
      76  res187                    initres1            res187     drawdown_days           sedres1           nutres1  
      77  res189                    initres1            res189     drawdown_days           sedres1           nutres1  
      78  res190                    initres1            res190     drawdown_days           sedres1           nutres1  
      79  res191                    initres1            res191     drawdown_days           sedres1           nutres1  
      80  res193                    initres1            res193     drawdown_days           sedres1           nutres1  
      81  res194                    initres1            res194     drawdown_days           sedres1           nutres1  
      82  res195                    initres1            res195     drawdown_days           sedres1           nutres1  
      83  res196                    initres1            res196     drawdown_days           sedres1           nutres1  
      84  res198                    initres1            res198     drawdown_days           sedres1           nutres1  
      85  res204                    initres1            res204     drawdown_days           sedres1           nutres1  
      86  res205                    initres1            res205     drawdown_days           sedres1           nutres1  
      87  res207                    initres1            res207     drawdown_days           sedres1           nutres1  
      88  res208                    initres1            res208     drawdown_days           sedres1           nutres1  
      89  res213                    initres1            res213     drawdown_days           sedres1           nutres1  
      90  res214                    initres1            res214     drawdown_days           sedres1           nutres1  
      91  res215                    initres1            res215     drawdown_days           sedres1           nutres1  
      92  res218                    initres1            res218     drawdown_days           sedres1           nutres1  
      93  res219                    initres1            res219     drawdown_days           sedres1           nutres1  
      94  res221                    initres1            res221     drawdown_days           sedres1           nutres1  
      95  res223                    initres1            res223     drawdown_days           sedres1           nutres1  
      96  res224                    initres1            res224     drawdown_days           sedres1           nutres1  
      97  res225                    initres1            res225     drawdown_days           sedres1           nutres1  
      98  res230                    initres1            res230     drawdown_days           sedres1           nutres1  
      99  res231                    initres1            res231     drawdown_days           sedres1           nutres1  
     100  res232                    initres1            res232     drawdown_days           sedres1           nutres1  
     101  res235                    initres1            res235     drawdown_days           sedres1           nutres1  
     102  res236                    initres1            res236     drawdown_days           sedres1           nutres1  
