name: docs

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
    paths:
      - '**/*.py'  # Any Python file anywhere in the repo
      - 'docs/**'  # Any file inside the docs folder
    tags:
      - "v*"  # Also deploy on release tags

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Allow pushing to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install MkDocs and dependencies
        run: uv pip install --system -r docs/requirements-docs.txt
                
      - name: Build MkDocs documentation
        run: |
          mkdocs build --site-dir public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public